"""
File: main.py
Purpose: FastAPI Entry Point for the Cognitive Engine.
1. Manages WebSocket connection with Unreal Engine 5.
2. Validates incoming Pydantic Models (GesPrompt).
3. Invokes the LangGraph workflow.
"""
from fastapi import FastAPI, WebSocket, WebSocketDisconnect
from .schemas.vr_context import GesPrompt
from .schemas.actions import ActionBatch
from .agents.state import AgentState
from .graph import app_graph
import json

app = FastAPI()

@app.get("/")
async def root():
    return {"message": "OmniAgent Cognitive Engine is running"}

@app.websocket("/ws/ue5")
async def websocket_ue5_endpoint(websocket: WebSocket):
    await websocket.accept()
    print("UE5 Client Connected")
    try:
        while True:
            # Receive raw JSON from UE5
            data = await websocket.receive_text()
            
            try:
                # 1. Validation (Strict Pydantic)
                input_data = json.loads(data)
                ges_prompt = GesPrompt(**input_data)
                print(f"Received GesPrompt from: {ges_prompt.player_id}")
                
                # 2. Build Initial State
                initial_state = AgentState(
                    messages=[],
                    vr_context=ges_prompt,
                    game_state=None, # In real implementation, this would be updated via MCP
                    next="",
                    current_speaker="",
                    analysis={},
                    action_batch=None
                )
                
                # 3. Run Graph
                print("Running Graph...")
                result = app_graph.invoke(initial_state)
                
                # 4. Extract Output
                final_action = result.get("action_batch")
                
                if final_action:
                    print(f"Graph Produced Action: {final_action.model_dump_json()}")
                    await websocket.send_text(final_action.model_dump_json())
                else:
                    # No action generated (maybe just internal thought or error)
                    error_batch = {
                        "agent_id": "System",
                        "actions": [],
                        "reasoning": "No action generated by agents."
                    }
                    await websocket.send_text(json.dumps(error_batch))
                
            except Exception as e:
                print(f"Processing Error: {e}")
                import traceback
                traceback.print_exc()
                await websocket.send_text(json.dumps({"error": str(e)}))
                
    except WebSocketDisconnect:
        print("UE5 Client Disconnected")
